### ISSUE TITLE
False results when querying for a set

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/pyfontaine#124]
Querying individual code points works well but whenever we try to query for a set such as uni-number-forms it says is fully supported while I know that is not.

Pic:

<img width="1332" alt="Screen Shot 2021-04-14 at 16 59 03" src="https://user-images.githubusercontent.com/48698976/114786001-13790500-9d43-11eb-86f7-2327ed14452f.png">

Resources to replicate: https://github.com/stipub/stixfonts/blob/master/fonts/static_ttf/STIXTwoMath-Regular.ttf

**Comment by felipesanches** [comment]
Interestingly, it works for me on Debian GNU/Linux:
![Screenshot from 2021-04-15 20-46-09](https://user-images.githubusercontent.com/213676/114951921-b311c280-9e2b-11eb-930e-1ededf4271dd.png)

On the other hand, if I run it without passing a specific set explicitly, then it seems to detect many sets as "full" support level, which is surely incorrect:
![Screenshot from 2021-04-15 20-52-46](https://user-images.githubusercontent.com/213676/114952409-945ffb80-9e2c-11eb-84ce-8e54e301a82d.png)

**Comment by felipesanches** [comment]
Inspecting it more thoroughly, the reported full sets seem to be accurate. **STIXTwo Math** contains almost 7 thousand glyphs.

**Comment by felipesanches** [comment]
so, I was not able to replicate @vv-monsalve's bug on my computer. I suspect the bad behaviour may be related to the error messages seen on her installation as described at #125 

I will later try to replicate this bug on MacOS as well.

**Comment by felipesanches** [comment]
No, it is not related to #125 because `uni-number-forms` does not use the pyicu module. Instead, it relies on fetching and parsing data directly from http://www.unicode.org/Public/UNIDATA/Blocks.txt

There may be bugs in the parsing of that data.

**Comment by felipesanches** [comment]
I've successfully installed pyfontaine from git main on my OSX laptop and it worked well:
<img width="1280" alt="Captura de Tela 2021-04-16 às 05 23 14" src="https://user-images.githubusercontent.com/213676/114995241-fe4fc380-9e73-11eb-80a4-5a410424428e.png">

**Comment by felipesanches** [comment]
I uninstalled fontaine from git (1.4.1-dev) and installed fontaine 1.4.0 form PyPI and I can see the problem. So it seems that we need to publish a new release so that people can benefit from the fix (it must have been fixed recently and I was not aware of it)

![Uploading Captura de Tela 2021-04-16 às 05.26.40.png…]()

**Comment by felipesanches** [comment]
@vv-monsalve For now, please git-clone pyfontaine and install it with `pip install -e .` form within the root of the repo dir.

**Comment by vv-monsalve** [comment]
> Inspecting it more thoroughly, the reported full sets seem to be accurate. **STIXTwo Math** contains almost 7 thousand glyphs.

Yes, 6760 as we saw the other day, but still it doesn't imply the sets are fully covered ;)

**Comment by vv-monsalve** [comment]
> @vv-monsalve For now, please git-clone pyfontaine and install it with `pip install -e .` form within the root of the repo dir.

We did run the `pip install https://github.com/googlefonts/pyfontaine/archive/main.zip` command at that moment and we got some Errors also (just in case).
I would try it with the `-e` mode and let you know

**Comment by vv-monsalve** [comment]
@felipesanches I've just [followed the new instructions](https://github.com/googlefonts/pyfontaine/issues/125#issuecomment-861707340), but I'm still receiving the same False Result

![Screen Shot 2021-06-15 at 11 59 55](https://user-images.githubusercontent.com/48698976/122100461-d7146480-cdd8-11eb-91ef-d45d1e19a520.png)

**Comment by vv-monsalve** [comment]
> @vv-monsalve For now, please git-clone pyfontaine and install it with `pip install -e .` form within the root of the repo dir.

I've cloned the repo, cd to it to be at the root, but `pip install -e` is not working. Perhaps I'm missing something, should I change to another directory into it or append anything else to the command?

**Comment by felipesanches** [comment]
did you include the dot in the command? There is a dot right after `-e `

**Comment by vv-monsalve** [comment]
> did you include the dot in the command? There is a dot right after `-e `

Mhm that was the missing part. I did it now and worked (under a venv).

![Screen Shot 2021-06-15 at 14 23 51](https://user-images.githubusercontent.com/48698976/122111492-6fb0e180-cde5-11eb-8171-25e9a302efb6.png)

**Comment by felipesanches** [comment]
Great! :-D
